repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    args: [-r, -c, .bandit.yml]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/netromdk/vermin
  rev: v1.6.0
  hooks:
  - id: vermin
    args: ['-t=3.10-', '--violations', '--eval-annotations', '--no-tips']
