exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "docs",
    ".github",
    "build",
    "dist",
    "tests",
    "benchmarks.py",
]

# Assume Python 3.10
target-version = "py310"
# Allow lines to be as long as 120.
line-length = 120

[lint]
select = ["E", "F", "W"]
ignore = ["E501", "F401", "F811"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
